import { AuthProvider } from "./Providers";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { useSession } from 'next-auth/react'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextAuth Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
